---
# file: roles/common/tasks/main.yml

- name: step 1 | check if system is already updated.
  yum:
    name="*" state=latest
  check_mode: true
  register: update

- name: step 2 | update all package
  become: yes
  become_user: root
  yum: name=* state=latest
  when: update.changed

- name: step 3 | check if package is already installed
  yum:
    pkg="{{install_list}}"
  check_mode: true
  register: pkg_installed

- name: Step 4 | install required packages
  become: yes
  become_user: root
  yum: pkg={{item}} state=installed
  with_items: 
   - '{{install_list}}'
  when: pkg_installed.changed

- name: step 5 | check cmake3 is installed or not
  shell: cmake3 --version
  register: check_cmake
  ignore_errors: True
  changed_when: False

- name : step 6 | installing cmake-3.6
  become: yes
  shell: yum install cmake3 -y
  when: check_cmake.rc > 0

- name: step 7 | Check that '{{ user }}' user exists or not.
  shell: grep "^{{user}}:" /etc/passwd
  ignore_errors: yes
  register: user_exist

- name: Step 8 | creating {{user}} user with admin access
  user: name='{{user}}' groups=wheel append=yes shell=/bin/bash createhome=yes state=present
  when: user_exist.rc > 0

- name: Step 9 | setting password for {{user}} user
  become: yes
  become_user: root
  shell: echo '{{user}}':'{{user}}' | sudo chpasswd
  when: user_exist.rc > 0

- name: Step 10 | allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  when: user_exist.rc > 0

- name: Step 11 | add users to wheel group
  user: name='{{user}}' groups=wheel append=yes
  when: user_exist.rc > 0

- name: Step 12 | setting entry in visudo.
  become: yes
  shell: echo 'zerocrack ALL=(ALL:ALL)' 'NOPASSWD':' ALL' | sudo EDITOR='tee -a' visudo
  when: user_exist.rc > 0

- name: step 13 | setting up /etc/security/limits.conf
  lineinfile: 
   path: /etc/security/limits.conf
   insertbefore: '# End of file'
   line: "{{ item }}"
  with_items:
    - "{{max_opening_filelimits}}"
    - "{{memory_lock}}"
    - "{{max_number_of_process}}"
    - "{{max_limits}}"

- name: step 14 | setting up /etc/sysctl.conf
  lineinfile:
   path: /etc/sysctl.conf
   insertbefore: '# End of file'
   line: "{{ item }}"
  with_items:
    - "vm.overcommit_memory=1"
    - "vm.max_map_count=262144"

- name: step 15 | setting up /etc/sysctl.conf
  become: yes
  become_user: root
  command: "{{ item }}"
  with_items:
    - sysctl -p --system

- name: Step 16 | updating /etc/hosts file
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:    
   - { src: "hosts", dest: "/etc/hosts" }

- name: step 17 | Comment out /etc/fstab in fstab
  replace:
    dest: /etc/fstab
    regexp: '^/dev/mapper/VolGroup00-LogVol01 swap                    swap    defaults        0 0'
    replace: '#/dev/mapper/VolGroup00-LogVol01 swap                    swap    defaults        0 0'
  tags: update-fstab

- name: Step 18 | disable firewall
  become: yes
  become_user: root
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Step 19 | flushing iptables
  become: yes
  become_user: root
  command: "{{ item }}"
  with_items:
   - iptables --flush

- name: Step 20 | Disable SELinux at next reboot
  selinux:
    state: disabled

- name: step 21 | Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false

- name: step 22 | check if ntp is installed
  yum:
    name=ntp state=installed
  check_mode: true
  register: ntp_install

- name: step 23 | install NTP
  become: yes
  become_user: root
  yum: name=ntp state=installed
  when: ntp_install.changed

- name: step 24 | ensure ntp is running
  service:
    name: ntpd
    state: started

- name: step 25 |  Checking home directory exist or not
  become: yes
  become_user: '{{user}}'
  stat:
   path: "{{HOME}}"
  register: folder_stats

- name: Step 26 | create home directory
  become: yes
  become_user: '{{user}}'
  file:
    path: '{{HOME}}'
    state: directory
    owner: '{{user}}'
    group: '{{user}}'
    mode: 0755
  when: not folder_stats.stat.exists

- name: Step 27 | create data directory
  become: yes
  become_user: '{{user}}'
  file:
    path: '{{DATA}}'
    state: directory
    owner: '{{user}}'
    group: '{{user}}'
    mode: 0755
  when: not folder_stats.stat.exists

- name: Step 28 | create logs directory
  become: yes
  become_user: '{{user}}'
  file:
    path: '{{LOGS}}'
    state: directory
    owner: '{{user}}'
    group: '{{user}}'
    mode: 0755
  when: not folder_stats.stat.exists

- name: Step 29 | create binaries directory
  become: yes
  become_user: '{{user}}'
  file:
    path: '{{BINARIES}}'
    state: directory
    owner: '{{user}}'
    group: '{{user}}'
    mode: 0755
  when: not folder_stats.stat.exists

- name: Step 30 | create services directory
  become: yes
  become_user: '{{user}}'
  file:
    path: '{{HOME}}/services'
    state: directory
    owner: '{{user}}'
    group: '{{user}}'
    mode: 0755
  when: not folder_stats.stat.exists

- name: step 31 |  Checking .ssh directory exist or not
  become: yes
  become_user: '{{user}}'
  stat:
   path: "{{ssh_directory}}"
  register: ssh_folder_stats

- name: step 32 | create ssh directory
  become: yes
  become_user: '{{user}}'
  file:
    path: '{{ssh_directory}}'
    state: directory
    owner: '{{user}}'
    group: '{{user}}'
    mode: 0700
  when: not ssh_folder_stats.stat.exists

- name: step 33 | checking private file exists or not.
  become: yes
  become_user: '{{user}}'
  stat:
    path: '{{ssh_directory}}/{{private_key_name}}'
  register: private_key

- name: step 34 | checking public key file exists or not.
  become: yes
  become_user: '{{user}}'
  stat:
    path: '{{ssh_directory}}/{{public_key_name}}'
  register: public_key

- name: step 35 | copying ssh keys
  become: yes
  become_user: '{{user}}'
  copy:
    src: templates/ssh-keys/{{ item }}
    dest: '{{ssh_directory}}/{{ item }}'
    owner: '{{user}}'
    group: '{{user}}'
    mode: 0600
  with_items:
    - "{{private_key_name}}"
    - "{{public_key_name}}"
    - config
  when: not private_key.stat.exists and not public_key.stat.exists

#- name: step 36 | copy config files
#  become_user: '{{user}}'
#  template: src={{ item.src }} dest={{ item.dest }}
#  mode: 0600
#  with_items: 
#   - { src: "./ssh-keys/config", dest: '{{ssh_directory}}' }

- name: step 37 | copying public key in authorized_keys.
  become_user: '{{user}}'
  remote_src: yes
  shell: "{{ item }} chdir={{ssh_directory}}"
  with_items:
    - 'cat {{public_key_name}} >> authorized_keys'
  when: not private_key.stat.exists and not public_key.stat.exists

- name: step 38 | changing directory permission
  become_user: '{{user}}'
  shell: 'chmod 700 {{ssh_directory}} && chmod 600 {{ssh_directory}}/*'

- name: step 39 | Checking java binary
  become: yes
  become_user: '{{user}}'
  stat:
   path: "{{BINARIES}}/{{java_binary}}"
  register: folder_stats

- name: step 40 | copy java-1.8 binary
  become: yes
  become_user: '{{user}}'
  copy:
    src: ./files/{{java_binary}}
    dest: '{{BINARIES}}'
    owner: '{{user}}'
    group: '{{user}}'
  when: not folder_stats.stat.exists

- name: step 41 | check java directory
  become: yes
  become_user: '{{user}}'
  stat:
   path: "{{java_home}}"
  register: folder_stats

- name: step 42 | extracting {{java_version}} binary
  become: yes
  become_user: '{{user}}'
  unarchive:
    src: ./files/{{java_binary}}
    dest: '{{HOME}}'
    owner: '{{user}}'
    group: '{{user}}'
  when: not folder_stats.stat.exists

- name: step 43 | Checking home directory
  become: yes
  become_user: '{{user}}'
  stat:
   path: "{{home_directory}}"
  register: folder_stats

- name: step 44 | copy envrc file
  template:
    src: ./env-file/envrc
    dest: '{{home_directory}}'
    owner: '{{user}}'
    group: '{{user}}'
  when: folder_stats.stat.exists

- name: step 45 | renaming envrc file
  command: mv /home/{{user}}/envrc /home/{{user}}/.envrc

- name: step 46 | Checking cfile exist or not
  become: yes
  become_user: '{{user}}'
  stat:
   path: '{{HOME}}/cfiles'
  register: folder_stats

- name: step 47 | create cfile directory
  file:
    path: '{{HOME}}/cfiles'
    state: directory
    owner: '{{user}}'
    group: '{{user}}'
  when: not folder_stats.stat.exists

- name: step 48 | copy crun and csync
  copy:
    src: templates/cfiles/{{ item }}
    dest: '{{HOME}}/cfiles/{{item}}'
    owner: '{{user}}'
    group: '{{user}}'
    mode: 0755
  when: not folder_stats.stat.exists
  with_items:
    - crun
    - csync

- name: step 49 | checking home directory
  become: yes
  become_user: '{{user}}'
  stat:
   path: "{{home_directory}}"
  register: folder_stats

- name: step 50 | copying cslaves files
  template:
    src: templates/env-file/cslaves
    dest: '{{home_directory}}'
    owner: '{{user}}'
    group: '{{user}}'
  when: folder_stats.stat.exists

- name: step 51 | copying script
  template:
    src: "{{item}}"
    dest: '{{HOME}}/services/'
    owner: '{{user}}'
    group: '{{user}}'
    mode: a+x
  when: folder_stats.stat.exists
  with_items:
   - templates/scripts/start.sh
   - templates/scripts/stop.sh
   - templates/scripts/start-firsttime.sh

- name: step 52 | renaming cslaves file
  command: mv {{home_directory}}/cslaves {{home_directory}}/.cslaves

- name: Step 53 | sync master time on all the machines
  command: echo {{user}} | sudo -S date --set="$(ssh {{ groups['master'][0] }} date)"

- name: step 54 | check java is installed or not
  shell: java -version
  register: check_java
  ignore_errors: True
  changed_when: False

- name: Step 55 | update alternatives
  command: "{{ item }}"
  when: check_java.rc > 0
  with_items:
   - update-alternatives --install "/usr/bin/java" "java" "{{HOME}}/jdk1.8.0_101/bin/java" 1
   - update-alternatives --install "/usr/bin/javac" "javac" "{{HOME}}/jdk1.8.0_101/bin/javac" 1
   - update-alternatives --install "/usr/bin/javaws" "javaws" "{{HOME}}/jdk1.8.0_101/bin/javaws" 1
   - update-alternatives --install "/usr/bin/jps" "jps" "{{HOME}}/jdk1.8.0_101/bin/jps" 1
   - update-alternatives --set java "{{HOME}}/jdk1.8.0_101/bin/java"
   - update-alternatives --set javac "{{HOME}}/jdk1.8.0_101/bin/javac"
   - update-alternatives --set javaws "{{HOME}}/jdk1.8.0_101/bin/javaws"
   - update-alternatives --set jps "{{HOME}}/jdk1.8.0_101/bin/jps"

#- name: step 56 | check node-js is installed or not
#  shell: node -v
#  register: check_node
#  ignore_errors: True
#  changed_when: False

#- name : step 57 | installing nodesource via curl
#  become_user: '{{user}}'
#  shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
#  when: check_node.rc > 0

#- name : step 58 | installing nodejs
#  become: yes
#  shell: yum install nodejs -y
#  when: check_node.rc > 0

- name: step 56 | copying kubernetes repo
  become: yes
  become_user: root
  copy:
    src: "templates/{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kubernetes.repo

- name: step 57 | Adding GPG key
  become: yes
  become_user: root
  rpm_key:
    state: present
    key:  https://packages.cloud.google.com/yum/doc/yum-key.gpg

- name: step 58 | copying kubernetes conf
  become: yes
  become_user: root
  copy:
    src: "templates/{{ item }}"
    dest: "/etc/sysctl.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - k8s.conf

- name: step 59 | Installing kubernetes package
  become: yes
  become_user: root
  command: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes 

- name: step 60 | copying docker daemon file
  become: yes
  become_user: root
  copy:
    src: "templates/{{ item }}"
    dest: "/etc/docker/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - daemon.json

- name: step 61 |enable service kubernetes and ensure it is not masked
  become: yes
  become_user: root
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items:
    - kubelet
    - docker
